### ISSUE TITLE
how to use mobilnetv3 to detect object in android ?

### ISSUE THREAD

**Issue by WestbrookZero** [Bisonai/quantized-mobilenetv3-mnist-android#1]

**Comment by martinkersner** [comment]
Hello @WestbrookZero!

In [Searching for MobileNetV3](https://arxiv.org/abs/1905.02244) they use MobileNetV3 as backbone feature  extractor in  [SSDLite](https://arxiv.org/abs/1801.04381). You would have to first modify the network to be able to predict the offsets to default boxes of different scales and aspect ratios and their associated confidences, include NMS to reduce the number of predicted bounded boxes and then retrain the model.

At https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android you can find detection demo for Android.

Cheers,
Martin

**Comment by WestbrookZero** [comment]
@martinkersner  thanks you. I used tensorflow object detection api to train MobileNetV3，https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssdlite_mobilenet_v3_large_320x320_coco.config, Android Project At https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android  ,but crash, my input image size is 320. because ssdlite_mobilenet_v3_large_320x320_coco.config , default is 320, I used mobilenetv2 input image size is 300 ,and is right not crash , I don't how to modify. android log error: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20 in tid 5931 (inference)
