### ISSUE TITLE
depthwise conv with depth_multiplier

### ISSUE THREAD

**Issue by cjtang** [Bisonai/quantized-mobilenetv3-mnist-android#2]
I have a question about the tflite model. May I ask why you try to use depthwise conv with depth_multiplier=16 as first layer but not  use the normal conv with output channel = 16 which is mentioned in the paper.

**Comment by martinkersner** [comment]
Hello @cjtang!

Thank you for pointing this out! This is caused by a typo in our model generation code where we commented out the first layer. There is no specific reason behind omitting the first regular convolutional layer. 

Cheers,
Martin

**Comment by cjtang** [comment]
Hi @martinkersner :

Thanks for reply. May I ask if you will fix this typo and update the model? I want to run this model on dsp, but now phone device's dsp doesn't support dwise conv with depth_multiplier.

**Comment by martinkersner** [comment]
Yes, we are going to fix it probably around this upcoming weekend. I will let you know when it is done.

**Comment by martinkersner** [comment]
Hi @cjtang 

We looked more into this issue and it seems that for training the first convolutional layer was actually used and defined as `tf.keras.layers.Conv2D`. Could you please show us what you were referring to?

Cheers,
Martin

**Comment by cjtang** [comment]
Hi @martinkersner 

When I downloaded the tflite model from github and viewed it in the Netron(model visualization tool), it shown that the first layer of model is depthwise conv with depth_multipler=16. If it was defined as tf.keras.layers.Conv2D when training, why after converted to tflite model it changed to depthwise conv operation?
![image](https://user-images.githubusercontent.com/29713800/63647324-3705bc80-c6d4-11e9-84ce-dd1039350084.png)

Thanks
Chunjue

**Comment by martinkersner** [comment]
@cjtang This is how the first layer looks like in Tensorboard.

<img src="https://i.imgur.com/NHxYaoS.png" />

I am not sure where it is changing to `DepthWiseConv2d`. It could happen during `tflite_convert` but I doubt it because it is nontrivial to split regular convolution to two separate ones without finetuning.

**Comment by cjtang** [comment]
Hi @martinkersner 

Yeah, it is very weird since the first layer of the model shown in Tensorboard is normal conv2d. If you don't mind, could you please share me the .pb file before tflite_convert? I have no clue of why tflite_convert change the normal Conv2d to DepthWiseConv2d.  

Thanks
Chunjue

**Comment by martinkersner** [comment]
@cjtang If you let me know your email address I will send you pb model file.

**Comment by cjtang** [comment]
@martinkersner 

My email is cjtang@uw.edu. Thank you very much.
